server:
  port: ${SERVER_PORT}

application:
  title: ${APP_TITLE}
  version: ${APP_VERSION}

info:
  app:
    name: ${APP_TITLE}
    description: ${APP_TITLE} ${APP_VERSION}
    version: ${APP_VERSION}

spring:
  application:
    name: eurekaserver

  profiles:
    active: dev

  config:
    import: configserver:http://localhost:8888/

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}

  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true